models:
  publisher:
    fields:
      name:
      authors:
        type: manytomany
        to: author

  author:
    fields:
      name:

  book:
    fields:
      name:
      author:
        type: foreignkey
        to: author